### ISSUE TITLE
ERROR using ESP32 target (AEGHB-452)

### ISSUE THREAD

**Issue by temistoclesCWClamper** [espressif/esp-mesh-lite#39]
Hi!

Example mesh_local_control build perfectly with target ESP32S3, but not with target ESP32 

I'm using Eclipse + IDF eclipse plugin 
ESP-IDF version = v4.4

Solving dependencies requirements
CMake Error at C:/dev/espressif/esp-idf-4.4.4/tools/cmake/build.cmake:452 (message):
................................................-- Configuring incomplete, errors occurred!
See also "C:/dev/espressif/esp32/mesh_lite/build/CMakeFiles/CMakeOutput.log".
  HINT: Component "espressif/usb_host_cdc_acm" has suitable versions for
  other targets: "esp32s3", "esp32s2".  Is your current target "esp32" set
  correctly?

  ERROR: Cannot find versions of "espressif/usb_host_cdc_acm" with version
  satisfying "2.*" for the current target "esp32"

Call Stack (most recent call first):
  C:/dev/espressif/esp-idf-4.4.4/tools/cmake/project.cmake:391 (idf_build_process)
  CMakeLists.txt:6 (project)

**Comment by tswen** [comment]
Two temporary solutions: 1 or 2.

1. Update pip and then update idf-component-manager to version 1.4.1.
```
pip install --upgrade pip
pip install idf-component-manager==1.4.1
```

2. Delete the build and dependencies.lock directories in managed_components.Remove the following content from main/idf_component.yml:
```
# The "esp_modem_usb_dte" component is temporarily disabled in iot_bridge yml file,
# as idf-component-manager doesn't support uploading components with "rules" entries to the registry.
# So temporarily place the "esp_modem_usb_dte" "esp_modem" component under examples.
#
espressif/esp_modem:
  version: 0.*
espressif/esp_modem_usb_dte:
  version: 1.*
  public: true
  rules:
    - if: "target in [esp32s2, esp32s3]"
    - if: "idf_version >= 4.4"
```
